#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

jobs:
- job: linux64
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      sh configure.sh
      sh build.sh
      zip -rq PeerTube.zip *
  - publish: $(System.DefaultWorkingDirectory)/PeerTube.zip
    artifact: PeerTube-linux64
